### ISSUE TITLE
Refuse to update NX 

### ISSUE THREAD

**Issue by Kalin-Konstantinov** [podkrepi-bg/api#144]
Cloning the main branch and installing the dependences, nx package refuse to upgrade the newest version and throw an error. Going some versions back, the problem do not occur and after execute the command yarn and update the last version of dependences, this problem reveal again.
If uninstall nx and install it again, the problem disappear finally.

**Comment by kachar** [comment]
We migrated `NX` to the current latest 13.x version with https://github.com/podkrepi-bg/api/pull/148

This issue should be fixed now
