### ISSUE TITLE
Make seeds exec only critical application data

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/api#15]
At the moment prisma seeds are running sample campaigns and they should be only adding static cities, campaign types and other fixed scope data.

> Populate your database with data that is required for your application to start - for example, a default language or a default currency.

https://www.prisma.io/docs/guides/database/seed-database

**Comment by igoychev** [comment]
This depends on what we want to use the seed records for. 
For migrations to work on production where the database will be full of production data, we need migratations to be very thoroughly tested. To achieve that, seeding all tables even for local dev environment will force us to write seamless migrations that will work on prod too.

**Comment by kachar** [comment]
Do we want to have two separate sets of seeds and execute them based on some environment variable?

**Comment by imilchev** [comment]
We discussed it with @kachar and concluded that default values such as campaign types should be in a migration and not as a seed. We should use the seed functionality only for dev/test data

**Comment by igoychev** [comment]
Yep, this works for me too! Migrations should add and transform data records as the database evolves.

**Comment by kachar** [comment]
Closing the issue as no further actions are required
