### ISSUE TITLE
Deploy api service in kubernetes environment

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/api#17]
Some initial manifests can be found at https://github.com/podkrepi-bg/api/tree/master/manifests

The env var `DATABASE_URL` needs to be set prior deployment

**Comment by imilchev** [comment]
What about the password for the db? Does it expect to have a schema already created for the module or something else?

**Comment by kachar** [comment]
Yep, the db schema needs to be initialized as in:

https://github.com/podkrepi-bg/api/blob/f26914f696993d6e3ba7975540f1620e2e4d6b1d/db/init.d/init.sql#L4

The whole `DATABASE_URL` needs to be a secret at this point, so we don't concat it.

The deployment has been done to dev.podkrepi.bg so I'm closing this issue. Feel free to reopen it if needs additional effort
