### ISSUE TITLE
Run API with local Keycloak instance instead of staging instance

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/api#205]
Several tasks are expected as a result of this card:

- [x] Add Keycloak to API `docker-compose.yml`
  - Sample keycloak docker-compose file can be found at https://github.com/podkrepi-bg/infrastructure/blob/main/keycloak/docker-compose.yml
- [x]  Load exported realm on init
  - Sample realm config can be found at https://github.com/podkrepi-bg/api/blob/master/manifests/keycloak-webapp-realm.json
- [x] Update README.md on how to use local Keycloak
- [x] Config in `.env` for local keycloak endpoint

**Comment by quantum-grit** [comment]
Done together with @borislavstoychev  in this PR: https://github.com/podkrepi-bg/api/pull/219

**Comment by Bunny303** [comment]
Done in https://github.com/podkrepi-bg/api/pull/219
