### ISSUE TITLE
[Bug] Wrong usage of sub property from type KeycloakTokenParsed

### ISSUE THREAD

**Issue by Bunny303** [podkrepi-bg/api#213]
When user is received from @AuthenticatedUser() user: KeycloakTokenParsed, the sub property equals to person.keycloakId.

In the cases below user.sub is used as person.id or campaign.coordinatorId and have to be fixed.
https://github.com/podkrepi-bg/api/blob/4c2e5af41ad5f80f52b9ad10a24a7c7dd10b2751/apps/api/src/donations/donations.controller.ts#L42

https://github.com/podkrepi-bg/api/blob/4c2e5af41ad5f80f52b9ad10a24a7c7dd10b2751/apps/api/src/vault/vault.controller.ts#L33
https://github.com/podkrepi-bg/api/blob/4c2e5af41ad5f80f52b9ad10a24a7c7dd10b2751/apps/api/src/vault/vault.controller.ts#L67

**Comment by kachar** [comment]
Reopening the issue as only the donation controller got fixed and the vault controller is still pending

cc @dimitur2204

**Comment by Bunny303** [comment]
A can fix the vault controller
