### ISSUE TITLE
[Feature] Add versioning and optimistic concurrency handling

### ISSUE THREAD

**Issue by stann1** [podkrepi-bg/api#276]
Note: will be an issue as prisma doesn't fully support this at the moment:

https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#optimistic-concurrency-control

**Comment by igoychev** [comment]
We have added transactions for handling donations amounts and vaults increments/decrements.
Closing the ticket with the suggestion to create separate issues for the specific logic in future
