### ISSUE TITLE
[API improvement] Swagger doc to display endpoints grouped by entity

### ISSUE THREAD

**Issue by quantum-grit** [podkrepi-bg/api#331]
## Current situation
Currently all endpoints in swagger appear on same level and make it confusing to find what you need.

## Why needed
The plan is to make the Swagger API public and announced on the Web UI, so we need it professionally looking

## Proposed solution
To group endponts by tags as per docs: https://docs.nestjs.com/openapi/operations#tags

**Comment by devkishor8007** [comment]
@igoychev please assign me, I want to do it!

**Comment by devkishor8007** [comment]
@igoychev thank you for assigning to me, please do check https://github.com/podkrepi-bg/api/pull/343

**Comment by igoychev** [comment]
solved in https://github.com/podkrepi-bg/api/pull/343
