### ISSUE TITLE
[Bug] Campaign list endpoint to not return description field

### ISSUE THREAD

**Issue by quantum-grit** [podkrepi-bg/api#332]
## Current Situation
Campaign list endpoint returns all fields of campaign record including long fields like description, that are not needed on UI.

## Desired Behaviour
The campaign list endpoint to return only the needed fields for Campaign list display on frontend/campaigns page.

**Comment by devkishor8007** [comment]
@quantum-grit what are the field should be shown to the Campaign list endpoint?

**Comment by devkishor8007** [comment]
@igoychev do assign me this task also!!
before assign, what are the field should be shown to the Campaign list endpoint?

**Comment by devkishor8007** [comment]
@igoychev @quantum-grit hello
which endpoint should be worked =>  [campaign/list]     [campaign/list-all]
Is this field should be shown only?
  =>
  title: string
  campaignTypeId: string
  beneficiaryId: string
  coordinatorId: string
  organizerId: string
  targetAmount: number
  allowDonationOnComplete?: boolean
  startDate: Date | string | undefined
  endDate: Date | string | undefined
  state: CampaignState
  description: string
  terms: boolean
  gdpr: boolean
}

thank you

**Comment by igoychev** [comment]
Hi again, @devkishor8007 

So there are two endpoints indeed:
1. for the endpoint [campaign/list] the expected fields are defined on line 79 type CampaignResponse in this file:
https://github.com/podkrepi-bg/frontend/blob/082c74038c550b4ec4468161eb61e5b5541417c3/src/gql/campaigns.ts#L79

2. for the endpoint [campaing/list-all] the expected fields are defined on line 49 type AdminCampaignResponse in this file:
https://github.com/podkrepi-bg/frontend/blob/082c74038c550b4ec4468161eb61e5b5541417c3/src/gql/campaigns.ts#L49

For selecting only the required fields, the Prisma query need to be changed by adding a select section where only required fields are listed like in the docs here: https://www.prisma.io/docs/concepts/components/prisma-client/select-fields#select-specific-fields

**Comment by devkishor8007** [comment]
@igoychev  please have a look and let me know if it is ok or not.
Thank you
