### ISSUE TITLE
[Feature] Integrate PSD2 listener for automated import of bank donations

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/api#358]
### Current Situation
Currently the donation made via bank transfer are imported manually in the system. For easier accounting and instant visibility we need automated approach.

### Desired Solution
Integrate a PSD2 bank API listener for receiving notifications for incoming bank transfer. We have already a contract to use IRIS's Solution platform free of charge. The IRIS API is described here: https://www.irisbgsf.com/api-documentation
Contact me for details.

**Comment by BogoCvetkov** [comment]
I'm taking this one
