### ISSUE TITLE
Seed donations

### ISSUE THREAD

**Issue by imilchev** [podkrepi-bg/api#364]
Currently, the seed data contains no donations. This makes it tricky to test donatioins-related functionality, especially in the frontend. It would be good to seed a few donations for at least one campaign to help frontend devs

**Comment by valkirilov** [comment]
Actually, there are some seeded `donations`, and they belong to the first campaign:
![image](https://user-images.githubusercontent.com/1233496/203137120-48806b47-a548-4c5b-baa6-9d619fe1233e.png)

And if we run the seeds script multiple times, it's adding more donation records for the campaign. Do you think that it's enough or it's still better to spend some time on this and seed `donations` for all campaigns (or at least for all seeded campaigns if there is a way how to differentiate them)?

![image](https://user-images.githubusercontent.com/1233496/203137708-253ea476-a4cb-41cc-b403-29eb52bdff67.png)

**Comment by batebobo** [comment]
Hi, I'd like to work on this. Can someone please assign me :pray:

**Comment by batebobo** [comment]
@imilchev I'm thinking of creating a fully funded (completed) campaign with 25 donations - it will cover both your points :) Do we have reasons to keep the completed campaign and the one with many donations as separate rows in the db?

**Comment by imilchev** [comment]
I think you can keep them. The more data we have, the better

**Comment by batebobo** [comment]
Hi! Can someone please close the issue :pray:
