### ISSUE TITLE
[Improvement] Add better database seeds

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/api#379]
We had a problem that broke production which we didn't catch neither from the backend, nor the frontend testing, due to insufficient and not true to life database seeds.

The exact case was that the `beneficiary` can be a company and not only a person. And on the frontend we had a call assuming `person` always exists, and the e2e tests didn't catch that since we didn't have such a case on the seeds.

They are one of the places where we can improve!

**Comment by batebobo** [comment]
It would be best if you could describe what exactly broke production and how you'd like to improve the seeds. Right now the task is too generic and It's not clear (to me) what the desired outcome is 🙏

**Comment by dimitur2204** [comment]
> The exact case was that the `beneficiary` can be a company and not only a person. And on the frontend we had a call assuming `person` always exists, and the e2e tests didn't catch that since we didn't have such a case on the seeds.

@batebobo
