### ISSUE TITLE
Upgrade Prisma version and related codebase

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/api#402]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Prisma, Seeds, Migrations

### Describe the feature you'd like to request

Upgrade Prisma packages from the current version `v4.3.1` to the latest stable version https://github.com/prisma/prisma/releases/tag/4.7.1

### Describe the solution you'd like

- update `package.json` versions
- check if db migrations docker images are being built OK
- check if db seeds work OK
- test if code generation and builds work normally

There might be breaking changes along the way

**Comment by devkishor8007** [comment]
@kachar can I do this task?

**Comment by quantum-grit** [comment]
closed with https://github.com/podkrepi-bg/api/pull/474
