### ISSUE TITLE
Create a Stripe mock and test the donation service

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/api#408]
### Describe the feature you'd like to request

We currently don't have any tests on the donation service. It would be a good idea to cover it since it's a crucial part of the application.

### Describe the solution you'd like

Create a mock of the Stripe client, here is something that might help: https://javascript.plainenglish.io/mock-stripe-api-in-node-js-with-jest-c9d8df595ff4,
There might a more NestJS way to do mocks though that we might use instead.

**Comment by igoychev** [comment]
Could you if the below will save some time:

There are already tests for stripe webhooks here:
https://github.com/podkrepi-bg/api/blob/master/apps/api/src/donations/events/stripe-payment.service.spec.ts
The tests already include a mock that allows testing the Stripe events for ensuring the webhooks are processing them correctly. 

There are also quite a lot of tests for the Donation service here:
https://github.com/podkrepi-bg/api/blob/master/apps/api/src/donations/donations.controller.spec.ts

**Comment by dimitur2204** [comment]
> Could you if the below will save some time:
> 
> There are already tests for stripe webhooks here: https://github.com/podkrepi-bg/api/blob/master/apps/api/src/donations/events/stripe-payment.service.spec.ts The tests already include a mock that allows testing the Stripe events for ensuring the webhooks are processing them correctly.
> 
> There are also quite a lot of tests for the Donation service here: https://github.com/podkrepi-bg/api/blob/master/apps/api/src/donations/donations.controller.spec.ts

I didn't see them. I was looking for tests only towards the donations.service directly. If that is the case than I am closing this issue!
