### ISSUE TITLE
Seed campaign messages

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/api#438]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Seeds

### Describe the feature you'd like to request

Currently we do not have campaign messages on local environment on Campaign details page:
![image](https://user-images.githubusercontent.com/14351733/218749057-8b025886-83db-41a3-9331-a14324a7a9a0.png)

### Describe the solution you'd like

In order to test Frontend functionality we need to seed some messages. They have to be more than 12 in order to be able to see the pagination.

**Comment by imilchev** [comment]
This seems to be already done
