### ISSUE TITLE
Add donated money in Donation Wishes

### ISSUE THREAD

**Issue by ani-kalpachka** [podkrepi-bg/api#444]
### Describe the feature you'd like to request

According to the new campaign details page design we should show the amount of donated money in the donation messages section:

![image](https://user-images.githubusercontent.com/14351733/220064363-c2305c6f-d375-4e30-83f6-0e6307063f15.png)

### Describe the solution you'd like

The donated money has to be added in the donationWish endpoint in order to be accessible from the frontend.

**Comment by AndreyGoranov** [comment]
@ani-kalpachka I would like to take it.

**Comment by Nnachevvv** [comment]
I would like to take this ticket :)
