### ISSUE TITLE
Financial Expenses - Expense entity

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/api#446]
### Describe the feature you'd like to request

Organizers need a way to upload expenses so that admins can approve/decline them. Check [#1316](https://github.com/podkrepi-bg/frontend/issues/1361).

### Describe the solution you'd like

* type* - string - hardcoded type of the expense synced with the financial team with an option for "Others" for non-standard types
* date* - Date - date of the expense
* amount* - number - amount of the expense
* currency* - string - currency of the expense
* description - string - description of what that expense consists of
* filesUrls* string[] - `.pdf`, `.jpg`, `.png` files  (should we allow other types?) which can be uploaded as proof of the expense on S3 bucket. **(Can possibly be more complex if we need to have "private"/"public" files!)**
* status - string - `awaiting` - awaiting approval, `declined` - declined by an admin, `approved` - approved by an admin and visible to the users.

Create endpoints for creation, update and deletion of the expenses, which should only be accessible to admins and organizers.

Normal users might not have access to all the details of the expense as admins and organizers!

RFC: Is it then a good idea to create 2 separate endpoints or 1 that returns different data based on role

**Comment by slavcho** [comment]
This is done imho.
