### ISSUE TITLE
Floating payment notifications with 0 sum

### ISSUE THREAD

**Issue by slavcho** [podkrepi-bg/api#506]
### Describe the Bug

Sometimes we can see floating notifications for payments with 0.0 on them.
I saw two of those today and managed to make a screenshot of one.

![image](https://github.com/podkrepi-bg/api/assets/99622/f2963885-8f1d-4a47-a72c-735482f9f60e)

### To Reproduce

Not sure how to reproduce it. Saw it by luck.

Here is the corresponding payment in stripe:
![image](https://github.com/podkrepi-bg/api/assets/99622/8efb5732-3091-47ac-b87f-f7b8d32737dd)

The payment is in a "waiting" state.

### Expected Behavior

Show only valid payments.

**Comment by sashko9807** [comment]
Perhaps expanding [this condition](https://github.com/podkrepi-bg/api/blob/6ffbcf145d578aa5baa4222f7894588035b87003/apps/api/src/campaign/campaign.service.ts#L489) to check if newDonationStatus is succeeded, will do the trick
