### ISSUE TITLE
Apply email templates

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/api#58]
Sources: https://drive.google.com/drive/u/1/folders/12baYqKnyo8V-W5B0B4oGPqUy-MZjlgWE

Template: https://mjml.io/try-it-live/vsZkuYmZx0O

Ask @anikolova-bg on Discord for latest versions

![image](https://user-images.githubusercontent.com/893608/144755775-211b5e0b-0bea-47da-882f-b6272982414d.png)

**Comment by kachar** [comment]
Link to MJML template for the emails https://gist.github.com/kachar/c2eea431fb2d19dfcfe20f414c5bdb0f

**Comment by kachar** [comment]
@podkrepi-bg/backend @podkrepi-bg/frontend Does anyone wants to help with this issue? 

We need to combine the email template with the predefined content and improve the welcome email experience.

**Comment by igoychev** [comment]
update: this was implemented long ago with adding the templates based on mjml, so closing now
