### ISSUE TITLE
Parts of the admin panel visible for the regular user

### ISSUE THREAD

**Issue by slavcho** [podkrepi-bg/api#642]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Authentication

### Summary
The admin panel should only be accessible for the administrators of the system.
When a regular user joins in, the admin panel url should be a 404 error page.
Same goes for all the urls like: 

/admin/campaigns

### Screenshot

![image](https://github.com/podkrepi-bg/api/assets/99622/068d5960-b528-4489-b5d8-17e9d6ad459b)

### To Reproduce

Login as a regular user.
Open the https://dev.podkrepi.bg/admin url.
Click on the menus on the left hand side.

### Expected Behavior

No access to any of the admin panels should be allowed for non admin users.

**Comment by sashko9807** [comment]
Fixed with [frontend#1854](https://github.com/podkrepi-bg/frontend/pull/1854)
