### ISSUE TITLE
[Campaign] Create endpoint for loading public campaign donation history

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/api#67]
The API should enable loading the details of the donation made for specific campaign.

Note, that anonymous donations should be loaded with Name=anonymous. 

The dataset should be selected from PrismaDb Client using Campaign.Vaults.Donations and for now only these fields are interesting donorName, donationAmount, donationTime

**Comment by kachar** [comment]
@igoychev Let's roll with `person: null` when we deal with anonymous donations. It makes it easier to check if there's a person object than to compare all places `person.firstName === 'anonymous'`

Filling in the first name and not other fields will make the person's object inconsistent.

**Comment by igoychev** [comment]
Yes, I am ok with person: null. My initial description was meant to say that name 'anonymous' should be 'displayed' in the UI.

**Comment by igoychev** [comment]
> @igoychev Let's roll with `person: null` when we deal with anonymous donations. It makes it easier to check if there's a person object than to compare all places `person.firstName === 'anonymous'`
> 
> Filling in the first name and not other fields will make the person's object inconsistent.
