### ISSUE TITLE
Nestjs warning about annotated imports

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/api#70]
```
cd api
yarn dev
```

> WARN [DependenciesScanner] In the next major version, Nest will not allow classes annotated with @Injectable(), @Catch(), and @Controller() decorators to appear in the "imports" array of a module.                                                                                                                                             
Please remove "JsonBodyMiddleware" (including forwarded occurrences, if any) from all of the "imports" arrays.                                                                               

> WARN [DependenciesScanner] In the next major version, Nest will not allow classes annotated with @Injectable(), @Catch(), and @Controller() decorators to appear in the "imports" array of a module.                                                                                                                                             
Please remove "RawBodyMiddleware" (including forwarded occurrences, if any) from all of the "imports" arrays.

> Scope [AppModule]

**Comment by kachar** [comment]
Opened discussion in package's repo https://github.com/golevelup/nestjs/discussions/385

**Comment by quantum-grit** [comment]
While upgrading nestjs to 9.1.4 it turned out the stripe middleware imports were not needed - tested and working well without them. The same was suggested also in the package's repo discussion: https://github.com/golevelup/nestjs/discussions/385
