### ISSUE TITLE
Bootcamp/ implement crud operations of entities

### ISSUE THREAD

**Issue by stilian-nikolaev** [podkrepi-bg/api#74]
Members of the team have chosen to implement the following models:

- [x] City - [Yakimov](https://github.com/Yakimov1337) and [PepiPetrov](https://github.com/PepiPetrov)
- [x] Country - [Dimitar Markov](https://github.com/dpmarkov)
- [x] BankAccount - [Ivan Kraev](https://github.com/ivankraev)
- [x] Document - [Stilian Nikolaev](https://github.com/stilian-nikolaev)
- [x] Campaign types - [PepiPetrov](https://github.com/PepiPetrov)
- [x] Person - [PepiPetrov](https://github.com/PepiPetrov)
- [x] Beneficiary - [PepiPetrov](https://github.com/PepiPetrov)
- [x] Coordinator - [Dimitar Dimitrov](https://github.com/dplamenov)
- [x] #88 - [dplamenov](https://github.com/dplamenov)
- [x] Donation - [Angelina Yakimova](https://github.com/angelina-7)
- [x] Expense - ~~[Petar Dzhunov](https://github.com/PetyrDzhunov)~~ [Dimitar Markov](https://github.com/dpmarkov)
- [x] Company - ~~[Todor Belchev](https://github.com/TodorBelchev)~~ [Needs help]

**Comment by kachar** [comment]
@TodorBelchev 
@PetyrDzhunov 

Please share if you're going to deliver the entities you're assigned to or we can distribute them to other contributors?

**Comment by PetyrDzhunov** [comment]
Distribute mine to other person , please :)

**Comment by TodorBelchev** [comment]
Distribute mine too.
