### ISSUE TITLE
[Bootcamp] Create CRUD for Coordinator entity

### ISSUE THREAD

**Issue by dplamenov** [podkrepi-bg/api#77]
Create CRUD for Coordinator entity
- [x] Create
- [x] Read
- [x] Update
- [x] Delete

**Comment by Polina1985** [comment]
Please, add picture in order to be more specific and easy for QA to test.

**Comment by dplamenov** [comment]
`I cannot Create a Coordinator.` - I can not reproduce this bug. Can you give more details?
`I cannot Update` - It's by design. Coordinator can't be updated. Defined by @igoychev
