### ISSUE TITLE
Integrate authorization layer

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/api#9]
- **Keycloak**
  - [x] https://www.npmjs.com/package/nest-keycloak-connect
  - [X] https://github.com/podkrepi-bg/api/issues/1
  - [x] #36

- **Casl**
  - [ ] https://casl.js.org/v5/en
  - [ ] Casl + Prisma https://casl.js.org/v5/en/package/casl-prisma

## Alternatives

 - **OSO**
   - https://docs.osohq.com/node/getting-started/quickstart.html
   - https://www.npmjs.com/package/nestjs-oso
   - https://github.com/osohq/oso-nest-doc-mgmt
   - Polar definitions
     - https://github.com/osohq/oso-nest-doc-mgmt/blob/main/src/oso/roles.polar
     - [Polar syntax](https://docs.osohq.com/python/reference/polar/polar-syntax.html)
- Nest Access Control 
  - https://github.com/nestjsx/nest-access-control

**Comment by igoychev** [comment]
We can consider this done - Auth layer with Keycloak is implemented and covered with tests
